
name: Author Labeler

on:
  pull_request:
  issues:

jobs:
  author-pr-labeler:
    name: Author PR labeler
    runs-on: ubuntu-latest
    if: github.event.pull_request.author_association != 'OWNER' &&  github.event.pull_request.author_association != 'MEMBER'

    steps:
      - name: Add Contributer Label
        uses: actions-ecosystem/action-add-labels@v1
        if: github.event.pull_request.author_association == 'COLLABORATOR' ||  github.event.pull_request.author_association == 'CONTRIBUTOR'
        with:
          labels: Community Contribution

  author-issue-labeler:
    name: Author Issue labeler
    runs-on: ubuntu-latest
    if: github.event.issue.author_association != 'OWNER' && github.event.issue.author_association != 'MEMBER'

    steps:
      - name: Add Contributer Label
        uses: actions-ecosystem/action-add-labels@v1
        if: github.event.issue.author_association == 'COLLABORATOR' ||  github.event.issue.author_association == 'CONTRIBUTOR'
        with:
          labels: Community Contribution
